<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2e1c9d18-60c7-417c-9916-9d67ebfceb24</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CorePortfolio.Domain\CorePortfolio.Domain.csproj" />
    <ProjectReference Include="..\CorePortfolio.Infrastructure\CorePortfolio.Infrastructure.csproj" />
    <ProjectReference Include="..\CorePortfolio.Coingecko\CorePortfolio.Coingecko.csproj" />
    <ProjectReference Include="..\CorePortfolio.Telegram\CorePortfolio.Telegram.csproj" />
    <ProjectReference Include="..\CorePortfolio.DNSE\CorePortfolio.DNSE.csproj" />
  </ItemGroup>

</Project>
