// <auto-generated />
using System;
using CorePortfolio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorePortfolio.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726043141_AddSprintZeroDataIntegrity")]
    partial class AddSprintZeroDataIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DefaultCurrency = "VND",
                            Name = "Fiat"
                        });
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "Currency")
                        .IsUnique();

                    b.ToTable("CashAccounts");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashflowRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CashAccountId");

                    b.HasIndex("CashflowRecordId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("CashLedgerEntries");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashflowCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("CashflowCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Color = "#10B981",
                            Icon = "💵",
                            IsGlobal = true,
                            Name = "Lương",
                            SortOrder = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("694f5dee-6171-4b45-be98-b12e46510a73"),
                            Color = "#10B981",
                            Icon = "💵",
                            IsGlobal = true,
                            Name = "Lương chính",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-000000000001"),
                            SortOrder = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Color = "#34D399",
                            Icon = "🎁",
                            IsGlobal = true,
                            Name = "Thưởng",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-000000000001"),
                            SortOrder = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("dd537949-bade-4d30-ac2a-62b6710b0fa7"),
                            Color = "#6EE7B7",
                            Icon = "🕒",
                            IsGlobal = true,
                            Name = "OT",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-000000000001"),
                            SortOrder = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Color = "#059669",
                            Icon = "💼",
                            IsGlobal = true,
                            Name = "Thu nhập phụ",
                            SortOrder = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("900175b4-e02d-4504-a20b-863206362b60"),
                            Color = "#059669",
                            Icon = "💻",
                            IsGlobal = true,
                            Name = "Freelance",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-000000000003"),
                            SortOrder = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("3e25eb4b-adb7-4fbc-b8ad-bf13093056d3"),
                            Color = "#047857",
                            Icon = "📦",
                            IsGlobal = true,
                            Name = "Bán hàng online",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-000000000003"),
                            SortOrder = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000001"),
                            Color = "#A7F3D0",
                            Icon = "🎁",
                            IsGlobal = true,
                            Name = "Khác",
                            SortOrder = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Color = "#EF4444",
                            Icon = "🍜",
                            IsGlobal = true,
                            Name = "Ăn uống",
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("6f8052ba-84d6-49db-b84a-2f8ef4643540"),
                            Color = "#EF4444",
                            Icon = "🍚",
                            IsGlobal = true,
                            Name = "Hằng ngày",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c34be7d4-b7cf-40b5-9120-adb21e7bb52a"),
                            Color = "#F87171",
                            Icon = "🍽️",
                            IsGlobal = true,
                            Name = "Ăn ngoài",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("df4c8022-9f49-4beb-94aa-397650e13b57"),
                            Color = "#FCA5A5",
                            Icon = "☕",
                            IsGlobal = true,
                            Name = "Coffee/Trà sữa",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000001"),
                            SortOrder = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000002"),
                            Color = "#F97316",
                            Icon = "🏠",
                            IsGlobal = true,
                            Name = "Chỗ ở & Cố định",
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Color = "#F97316",
                            Icon = "🏘️",
                            IsGlobal = true,
                            Name = "Tiền nhà",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000002"),
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("e45cb584-d6bf-44e0-beeb-5bc1cb3960cb"),
                            Color = "#FB923C",
                            Icon = "⚡",
                            IsGlobal = true,
                            Name = "Điện",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000002"),
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("5fc975e0-42f1-4fe4-bd58-45d6853a54e5"),
                            Color = "#FDBA74",
                            Icon = "💧",
                            IsGlobal = true,
                            Name = "Nước",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000002"),
                            SortOrder = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("66292db5-3c78-4892-ae54-b93e40d14a7b"),
                            Color = "#FFEDD5",
                            Icon = "🌐",
                            IsGlobal = true,
                            Name = "Internet",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000002"),
                            SortOrder = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Color = "#EAB308",
                            Icon = "🚗",
                            IsGlobal = true,
                            Name = "Di chuyển",
                            SortOrder = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("8ab71e3f-24bf-498f-b04b-4b053c2a0b3a"),
                            Color = "#EAB308",
                            Icon = "⛽",
                            IsGlobal = true,
                            Name = "Xăng xe",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000003"),
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("1e3efabd-a3bd-4584-82fd-122d282fa63d"),
                            Color = "#FACC15",
                            Icon = "🚕",
                            IsGlobal = true,
                            Name = "Grab/Taxi",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000003"),
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("61930dcc-89b9-43db-a3fb-8d17279be178"),
                            Color = "#FEF08A",
                            Icon = "🔧",
                            IsGlobal = true,
                            Name = "Bảo dưỡng xe",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000003"),
                            SortOrder = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000003"),
                            Color = "#3B82F6",
                            Icon = "🧴",
                            IsGlobal = true,
                            Name = "Sinh hoạt & Cá nhân",
                            SortOrder = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("3b4c2644-2aac-4eee-b147-a24f15369ab2"),
                            Color = "#3B82F6",
                            Icon = "🛒",
                            IsGlobal = true,
                            Name = "Đồ dùng sinh hoạt",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000003"),
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a53443b6-aeb0-4b3b-8e41-215ec23acd4a"),
                            Color = "#60A5FA",
                            Icon = "👕",
                            IsGlobal = true,
                            Name = "Quần áo",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000003"),
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("fb25f644-e903-47de-a5a6-e4f2018e4a4f"),
                            Color = "#93C5FD",
                            Icon = "✂️",
                            IsGlobal = true,
                            Name = "Cắt tóc",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000003"),
                            SortOrder = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("4b31b1d3-e5e3-4423-8ce2-03a0b2c707e0"),
                            Color = "#BFDBFE",
                            Icon = "💊",
                            IsGlobal = true,
                            Name = "Y tế",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000003"),
                            SortOrder = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Color = "#DC2626",
                            Icon = "🛍️",
                            IsGlobal = true,
                            Name = "Mua sắm",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000003"),
                            SortOrder = 5,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000004"),
                            Color = "#EC4899",
                            Icon = "🎁",
                            IsGlobal = true,
                            Name = "Quan hệ xã hội",
                            SortOrder = 5,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c50f14de-c0cc-4de1-926a-40252384f0b0"),
                            Color = "#EC4899",
                            Icon = "💌",
                            IsGlobal = true,
                            Name = "Hiếu hỉ",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000004"),
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("af1f5f06-79b7-4888-80cd-86d4695a8072"),
                            Color = "#F472B6",
                            Icon = "🎁",
                            IsGlobal = true,
                            Name = "Quà tặng",
                            ParentCategoryId = new Guid("00000000-0000-0000-0001-a00000000004"),
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Color = "#8B5CF6",
                            Icon = "🎭",
                            IsGlobal = true,
                            Name = "Giải trí",
                            SortOrder = 6,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("3ec84eb1-f674-4db2-acae-5b95b5552c63"),
                            Color = "#8B5CF6",
                            Icon = "🎬",
                            IsGlobal = true,
                            Name = "Xem phim",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000004"),
                            SortOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("b46a571f-7c9d-4b73-b3a3-da32fb178a5e"),
                            Color = "#A78BFA",
                            Icon = "🎮",
                            IsGlobal = true,
                            Name = "Game/Sub",
                            ParentCategoryId = new Guid("00000000-0000-0000-0002-000000000004"),
                            SortOrder = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000005"),
                            Color = "#06B6D4",
                            Icon = "✈️",
                            IsGlobal = true,
                            Name = "Du lịch",
                            SortOrder = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000006"),
                            Color = "#14B8A6",
                            Icon = "📚",
                            IsGlobal = true,
                            Name = "Học tập",
                            SortOrder = 8,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-a00000000007"),
                            Color = "#64748B",
                            Icon = "❓",
                            IsGlobal = true,
                            Name = "Khác",
                            SortOrder = 9,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Color = "#8B5CF6",
                            Icon = "📈",
                            IsGlobal = true,
                            Name = "Đầu tư",
                            SortOrder = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("773de4db-23b8-41b3-b752-140e3fc71a23"),
                            Color = "#8B5CF6",
                            Icon = "₿",
                            IsGlobal = true,
                            Name = "Crypto",
                            ParentCategoryId = new Guid("00000000-0000-0000-0003-000000000001"),
                            SortOrder = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("b6820223-9133-4b7c-b77e-bc17b40df075"),
                            Color = "#A78BFA",
                            Icon = "📊",
                            IsGlobal = true,
                            Name = "Cổ phiếu",
                            ParentCategoryId = new Guid("00000000-0000-0000-0003-000000000001"),
                            SortOrder = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("ccdaf802-c248-439f-9d8a-7c22ee25e3d8"),
                            Color = "#C4B5FD",
                            Icon = "🏦",
                            IsGlobal = true,
                            Name = "Chứng chỉ quỹ",
                            ParentCategoryId = new Guid("00000000-0000-0000-0003-000000000001"),
                            SortOrder = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Color = "#0EA5E9",
                            Icon = "💰",
                            IsGlobal = true,
                            Name = "Tiết kiệm",
                            SortOrder = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("fcae34ef-35d9-4cfa-beb1-2cc6838f6bd9"),
                            Color = "#0EA5E9",
                            Icon = "🛡️",
                            IsGlobal = true,
                            Name = "Quỹ khẩn cấp",
                            ParentCategoryId = new Guid("00000000-0000-0000-0004-000000000001"),
                            SortOrder = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("00fc27d6-be2a-4cfb-99aa-5ae00b0d4617"),
                            Color = "#38BDF8",
                            Icon = "🏦",
                            IsGlobal = true,
                            Name = "Gửi ngân hàng",
                            ParentCategoryId = new Guid("00000000-0000-0000-0004-000000000001"),
                            SortOrder = 2,
                            Type = 4
                        });
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashflowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("CashflowRecords");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.DcaPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MarketAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("UserId");

                    b.ToTable("DcaPlans");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.MarketAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPriceError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MarketAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CurrentPrice = 1m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "VND Cash",
                            PriceSource = "Manual",
                            PriceStatus = "Manual",
                            Symbol = "VND"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CurrentPrice = 1m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "USD Cash",
                            PriceSource = "Manual",
                            PriceStatus = "Manual",
                            Symbol = "USD"
                        });
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "DedupeKey")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsdToVndRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValuationTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "Date")
                        .IsUnique();

                    b.ToTable("PortfolioSnapshots");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RebalanceExecutionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvailableCash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RebalanceExecutionPlans");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RebalanceExecutionPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExecutableAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCashLimited")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SuggestedAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlanId");

                    b.ToTable("RebalanceExecutionPlanItems");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RecurringCashflowRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextOccurrence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("UserId", "NextOccurrence");

                    b.ToTable("RecurringCashflowRules");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.SavingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashflowCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashAccountId");

                    b.HasIndex("CashflowCategoryId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("UserId");

                    b.ToTable("SavingGoals");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "USD_TO_VND",
                            Description = "Exchange rate from USD to VND",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "26309"
                        });
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.TargetAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPercentage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("TargetAllocations");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Role", "IsActive");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarketAssetId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketAssetId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Asset", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Assets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketAsset");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Budget", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.CashflowCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashAccount", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("CashAccounts")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashLedgerEntry", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.CashAccount", "CashAccount")
                        .WithMany("Entries")
                        .HasForeignKey("CashAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.CashflowRecord", "CashflowRecord")
                        .WithMany()
                        .HasForeignKey("CashflowRecordId");

                    b.HasOne("CorePortfolio.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CashAccount");

                    b.Navigation("CashflowRecord");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashflowCategory", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.CashflowCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany("CustomCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashflowRecord", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.CashflowCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("CashflowRecords")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany("CashflowRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Portfolio");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.DcaPlan", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketAsset");

                    b.Navigation("Portfolio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.MarketAsset", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.AssetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Snapshots")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RebalanceExecutionPlan", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RebalanceExecutionPlanItem", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.AssetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.RebalanceExecutionPlan", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RecurringCashflowRule", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.CashflowCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Portfolio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.SavingGoal", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.CashAccount", "CashAccount")
                        .WithMany()
                        .HasForeignKey("CashAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorePortfolio.Domain.Entities.CashflowCategory", "CashflowCategory")
                        .WithMany()
                        .HasForeignKey("CashflowCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashAccount");

                    b.Navigation("CashflowCategory");

                    b.Navigation("Portfolio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.TargetAllocation", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.AssetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany("TargetAllocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("CorePortfolio.Domain.Entities.MarketAsset", "MarketAsset")
                        .WithMany()
                        .HasForeignKey("MarketAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorePortfolio.Domain.Entities.User", "User")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketAsset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashAccount", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.CashflowCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("CashAccounts");

                    b.Navigation("CashflowRecords");

                    b.Navigation("Snapshots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.RebalanceExecutionPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CorePortfolio.Domain.Entities.User", b =>
                {
                    b.Navigation("CashflowRecords");

                    b.Navigation("CustomCategories");

                    b.Navigation("Portfolios");

                    b.Navigation("TargetAllocations");

                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
