name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' 
      
      - name: Restore dependencies
        run: dotnet restore backend/CorePortfolio.slnx
        
      - name: Build with dotnet
        run: dotnet build backend/CorePortfolio.slnx --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/src/CorePortfolio.API/CorePortfolio.API.csproj -c Release -r linux-x64 --self-contained true -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'coreportfolio-api-cdbchffjhtg2hgda' 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{env.DOTNET_ROOT}}/myapp