name: CD - Auto Deploy to Local Server

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy
      run: |
        cd /home/hieu-mai-trong/Project/CorePortfolio
        git reset --hard
        git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hieumt24/CorePortfolio.git main
        
        cd frontend
        npm ci
        npm run build
        
        cd ../backend
        dotnet restore CorePortfolio.slnx
        dotnet build CorePortfolio.slnx -c Release
        
        pm2 restart ecosystem.config.js
